import NavBar from "@/components/NavBar";
import "./globals.css";

export const metadata = {
    title: "Tienline",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-slate-200">
                <NavBar></NavBar>
                {children}
            </body>
        </html>
    );
}
